ALTER TABLE forms ADD COLUMN use_tag_in_description BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE forms ADD COLUMN use_tag_in_message_input BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE forms ADD COLUMN use_tag_in_message_confirm BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE forms ADD COLUMN use_tag_in_message_complete BOOLEAN NOT NULL DEFAULT FALSE;
